Algoritmo "consumoDoCarro"

Var
 distancia1,kml2,efi: real

funcao consumoDoCarro (distancia,kml:real) :real
var
conta1:real
consumo : real

inicio


conta1:= (distancia1/kml2)
 retorne conta1


   fimfuncao

Inicio

escreval("digite a distancia em (KM) ")
   leia(distancia1)
   escreval("digite quanto o veiculo faz por litro" )
   leia(kml2)

   efi:= consumoDoCarro(distancia1,kml2)
   escreval(efi)
   
   





Fimalgoritmo