algoritmo "dois numeros, maior deles 23"


var
sexo:caracter;

inicio

escreval("se voce for mulher digite f e se for homen digite m",sexo)
leia(sexo)

se  sexo = "f" entao
    escreval("voce é mulher")
     senao

      se  sexo = "m"  entao
        escreval("voce é homen")
         senao

          escreval("sexo invalido")
          fimse
         fimse








fimalgoritmo
