Algoritmo "fumante"

Var
numero,dinheiro,tempo1,perdidos,meses,ante,suce,dobro,terco,dolar,cigarro,vida: real;


Inicio

escreval("quantos cigarros voce fuma por dia?:", cigarro)
leia(cigarro)
escreval("A quanto tempo voce fuma (em anos) ?:", tempo1)
leia(tempo1)
meses:= (tempo1*365)*(cigarro)*10
perdidos:= meses/1440







escreval(perdidos)













Fimalgoritmo