Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/10/2024
var
  num1, num2, soma: inteiro
inicio
  escreval("Digite o primeiro número: ")
  leia(num1)
  escreval("Digite o segundo número: ")
  leia(num2)
  soma := num1 + num2
  escreval("A soma dos números é: ", soma)
fimalgoritmo
